version: 2
sources:
  - name: raw              # alias pour dbt
    schema: gz_raw_data    # vrai dataset BigQuery
    tables:
      - name: sales        # alias pour dbt
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      - name: ship
        identifier: raw_gz_ship